-- SQL DDL: create table for DSE market OHLCV data
-- Drop existing table if we want to recreate, or just let the user run it on an empty database.
-- For safety, we just redefine it assuming it can be recreated. 
-- In a real scenario, you might want to drop it first if it exists: DROP TABLE IF EXISTS public.dse_market_snapshots;

CREATE TABLE IF NOT EXISTS public.dse_market_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  ticker TEXT NOT NULL,
  open NUMERIC(20,4),
  high NUMERIC(20,4),
  low NUMERIC(20,4),
  close NUMERIC(20,4) NOT NULL,
  volume BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT dse_market_snapshots_ticker_date_key UNIQUE (ticker, date)
);

-- Enable Row Level Security (service_role still bypasses this)
ALTER TABLE public.dse_market_snapshots ENABLE ROW LEVEL SECURITY;

-- Helpful index for queries by ticker and date
CREATE INDEX IF NOT EXISTS idx_dse_market_snapshots_ticker_date
  ON public.dse_market_snapshots (ticker, date DESC);

-- Note: Use the Supabase 'service_role' key for server-side writes (it bypasses RLS).