-- SQL DDL: create table for DSE market snapshots

CREATE TABLE IF NOT EXISTS public.dse_market_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ticker TEXT NOT NULL,
  price NUMERIC(20,4) NOT NULL,
  volume BIGINT
);

-- Disable Row Level Security so service_role can write without RLS
ALTER TABLE public.dse_market_snapshots DISABLE ROW LEVEL SECURITY;

-- Helpful index for queries by ticker and recent snapshots
CREATE INDEX IF NOT EXISTS idx_dse_market_snapshots_ticker_created_at
  ON public.dse_market_snapshots (ticker, created_at DESC);

-- Note: Use the Supabase 'service_role' key for server-side writes (it bypasses RLS).