-- SQL DDL: create table and trigger for dynamic price alerts via Telegram
-- Run this in your Supabase SQL Editor

-- 1. Create price_alerts table
CREATE TABLE IF NOT EXISTS public.price_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL,
  target_price NUMERIC(20,4) NOT NULL,
  condition TEXT CHECK (condition IN ('ABOVE', 'BELOW')) NOT NULL,
  recipient TEXT NOT NULL, -- Telegram Chat ID
  is_active BOOLEAN DEFAULT true,
  last_triggered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Helpful index for active alerts lookup by ticker
CREATE INDEX IF NOT EXISTS idx_price_alerts_ticker_active 
  ON public.price_alerts (ticker, is_active);

-- Enable RLS (service role bypasses it)
ALTER TABLE public.price_alerts ENABLE ROW LEVEL SECURITY;

-- 2. Enable pg_net extension for async HTTP requests from Postgres
CREATE EXTENSION IF NOT EXISTS pg_net;

-- 3. Alert Evaluator & Notification Function
CREATE OR REPLACE FUNCTION check_dse_price_alerts()
RETURNS TRIGGER AS $$
DECLARE
    alert_rec RECORD;
    -- Set your Telegram Bot Token here for pg_net trigger:
    telegram_bot_token TEXT := '8878847897:AAFVdB0Pc4BAQbbwwShwQXRsLuycATKvQPI';
    msg TEXT;
    symbol TEXT;
BEGIN
    -- Ignore rows without valid ticker or close price
    IF NEW.ticker IS NULL OR NEW.close IS NULL THEN
        RETURN NEW;
    END IF;

    -- Loop through active alerts matching the updated ticker
    FOR alert_rec IN 
        SELECT id, target_price, condition, recipient 
        FROM public.price_alerts 
        WHERE ticker = UPPER(NEW.ticker)
          AND is_active = true 
          AND (
              (condition = 'ABOVE' AND NEW.close >= target_price) OR 
              (condition = 'BELOW' AND NEW.close <= target_price)
          )
    LOOP
        -- Choose status emoji
        IF alert_rec.condition = 'ABOVE' THEN
            symbol := '📈';
        ELSE
            symbol := '📉';
        END IF;

        -- Format Telegram Markdown message
        msg := '🚨 *DSE PRICE ALERT* ' || symbol || E'\n\n' ||
               '📌 *Stock:* `' || NEW.ticker || '`' || E'\n' ||
               '💰 *Current Price:* *' || NEW.close || ' BDT*' || E'\n' ||
               '🎯 *Target Price:* *' || alert_rec.target_price || ' BDT* (' || alert_rec.condition || ')';

        -- Send HTTP POST to Telegram API via pg_net
        PERFORM net.http_post(
            url := 'https://api.telegram.org/bot' || telegram_bot_token || '/sendMessage',
            headers := '{"Content-Type": "application/json"}'::jsonb,
            body := jsonb_build_object(
                'chat_id', alert_rec.recipient,
                'text', msg,
                'parse_mode', 'Markdown'
            )
        );

        -- Deactivate alert to prevent repeated spam notifications
        UPDATE public.price_alerts 
        SET is_active = false, last_triggered_at = NOW() 
        WHERE id = alert_rec.id;

    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Create trigger on dse_market_snapshots table
DROP TRIGGER IF EXISTS trigger_check_dse_price_alerts ON public.dse_market_snapshots;
CREATE TRIGGER trigger_check_dse_price_alerts
AFTER INSERT OR UPDATE ON public.dse_market_snapshots
FOR EACH ROW
EXECUTE FUNCTION check_dse_price_alerts();
